// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJ6fyfyjVExwYXsUM-tKkMfuYywkpM-s',
    appId: '1:556209962168:web:aaed5a20d4b50a5d72884d',
    messagingSenderId: '556209962168',
    projectId: 'aurivo-cc64c',
    authDomain: 'aurivo-cc64c.firebaseapp.com',
    storageBucket: 'aurivo-cc64c.firebasestorage.app',
    measurementId: 'G-R8DZ6JMF6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkxcBoQCmzkGYSBHNh6TMuyx72o4IDLQ',
    appId: '1:556209962168:android:9960ea543ddcfa7c72884d',
    messagingSenderId: '556209962168',
    projectId: 'aurivo-cc64c',
    storageBucket: 'aurivo-cc64c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtAVsAcvdahDX6Uqm-z3xJ7lt78B_4m3M',
    appId: '1:556209962168:ios:3658d4890154ab1472884d',
    messagingSenderId: '556209962168',
    projectId: 'aurivo-cc64c',
    storageBucket: 'aurivo-cc64c.firebasestorage.app',
    iosBundleId: 'com.example.aurivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtAVsAcvdahDX6Uqm-z3xJ7lt78B_4m3M',
    appId: '1:556209962168:ios:3658d4890154ab1472884d',
    messagingSenderId: '556209962168',
    projectId: 'aurivo-cc64c',
    storageBucket: 'aurivo-cc64c.firebasestorage.app',
    iosBundleId: 'com.example.aurivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJ6fyfyjVExwYXsUM-tKkMfuYywkpM-s',
    appId: '1:556209962168:web:2fd458ecf97a3b5272884d',
    messagingSenderId: '556209962168',
    projectId: 'aurivo-cc64c',
    authDomain: 'aurivo-cc64c.firebaseapp.com',
    storageBucket: 'aurivo-cc64c.firebasestorage.app',
    measurementId: 'G-PXC89WQP3Z',
  );
}
