-- Phase 13C hardening / migration 20 — constrain notifications.type.
-- Applied live as migration 20_notifications_type_check.
--
-- Locks the type column to the known vocabulary: the four types actually
-- generated by migrations 15/17/18/19 (order_update, seller_event,
-- chat_message, support) plus three reserved from the notification_templates
-- vocabulary (otp, promotion, system) for future use. Data-integrity only;
-- RLS/grants unchanged; notification_templates untouched; realtime untouched.
-- Uses NOT VALID + VALIDATE (production-safe pattern even though the table is
-- currently empty).

alter table public.notifications
  add constraint notifications_type_check
  check (
    type = any (
      array[
        'order_update',
        'seller_event',
        'chat_message',
        'support',
        'otp',
        'promotion',
        'system'
      ]
    )
  ) not valid;

alter table public.notifications
  validate constraint notifications_type_check;
